elixhauser_indexes = {
    "congestive_heart_failure": False,
    "cardiac_arrhythmia": False,
    "valvular_disease": False,
    "pulmonary_circulation_disorder": False,
    "peripheral_vascular_disease": False,
    "hypertension_uncomplicated": False,
    "hypertension_complicated": False,
    "paralysis": False,
    "other_neurological_disorders": False,
    "chronic_pulmonary_disease": False,
    "diabetes_uncomplicated": False,
    "diabetes_complicated": False,
    "hypothyroidism": False,
    "renal_failure": False,
    "liver_disease": False,
    "peptic_ulcer_disease": False,
    "aids_hiv": False,
    "lymphoma": False,
    "metastatic_cancer": False,
    "solid_tumor_without_metastasis": False,
    "rheumatoid_arthritis_collagen_vascular": False,
    "coagulopathy": False,
    "obesity": False,
    "weight_loss": False,
    "fluid_electrolyte_disorders": False,
    "blood_loss_anemia": False,
    "deficiency_anemia": False,
    "alcohol_abuse": False,
    "drug_abuse": False,
    "psychoses": False,
    "depression": False
}

print(elixhauser_indexes)
