cci_indexes = [
    {"condition": "Myocardial infarction", "variable": "MI", "points": 1, "notes": ""},
    {"condition": "Congestive heart failure", "variable": "CHF", "points": 1, "notes": ""},
    {
        "condition": "Peripheral vascular disease or bypass",
        "variable": "PVD",
        "points": 1,
        "notes": "",
    },
    {
        "condition": "Cerebrovascular disease or transient ischemic disease",
        "variable": "CVA",
        "points": 1,
        "notes": "CVA only",
    },
    {
        "condition": "Hemiplegia",
        "variable": "PLEGIA",
        "points": 2,
        "notes": "If hemiplegia, do not count CVA separately",
    },
    {"condition": "Pulmonary disease / asthma", "variable": "COPD", "points": 1, "notes": ""},
    {"condition": "Diabetes", "variable": "DM", "points": 1, "notes": "DM only"},
    {
        "condition": "Diabetes with end organ damage",
        "variable": "DMENDORGAN",
        "points": 2,
        "notes": "If end organ damage, do not count DM separately",
    },
    {"condition": "Renal disease", "variable": "RENAL", "points": 2, "notes": ""},
    {"condition": "Mild liver disease", "variable": "MILD_LIVER", "points": 2, "notes": ""},
    {"condition": "Severe liver disease", "variable": "SEVERE_LIVER", "points": 3, "notes": ""},
    {"condition": "Gastric or peptic ulcer", "variable": "ULCER", "points": 1, "notes": ""},
    {
        "condition": "Cancer (lymphoma, leukemia, solid tumor)",
        "variable": "CANCER",
        "points": 2,
        "notes": "Nonmetastatic cancer only",
    },
    {
        "condition": "Metastatic solid tumor",
        "variable": "METASTASES",
        "points": 6,
        "notes": "If metastatic, do not count cancer separately",
    },
    {"condition": "Dementia or Alzheimer’s", "variable": "DEMENTIA", "points": 1, "notes": ""},
    {
        "condition": "Rheumatic or connective tissue disease",
        "variable": "RHEUMATIC",
        "points": 1,
        "notes": "",
    },
    {"condition": "HIV or AIDS", "variable": "HIV", "points": 6, "notes": ""},
    {"condition": "Hypertension", "variable": "HBP", "points": 1, "notes": ""},
    {"condition": "Skin ulcers / cellulitis", "variable": "SKIN_ULCER", "points": 2, "notes": ""},
    {"condition": "Depression", "variable": "DEPRESSION", "points": 1, "notes": ""},
    {"condition": "Warfarin use", "variable": "WARFARIN", "points": 1, "notes": ""},
]


cci_mapping = {
    "MI": 1,
    "CHF": 1,
    "PVD": 1,
    "CVA": 1,
    "PLEGIA": 2,
    "COPD": 1,
    "DM": 1,
    "DMENDORGAN": 2,
    "RENAL": 2,
    "MILD_LIVER": 2,
    "SEVERE_LIVER": 3,
    "ULCER": 1,
    "CANCER": 2,
    "METASTASES": 6,
    "DEMENTIA": 1,
    "RHEUMATIC": 1,
    "HIV": 6,
    "HBP": 1,
    "SKIN_ULCER": 2,
    "DEPRESSION": 1,
    "WARFARIN": 1,
}

print(len(cci_indexes))
